<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.27.0.140913" />
    <PackageVersion Include="Figgle.Fonts" Version="0.6.6" />
    <PackageVersion Include="Serilog" Version="4.3.1" />
    <PackageVersion Include="WebSystemTools.ApiExceptionHandler" Version="1.0.9686.34761" />
    <PackageVersion Include="WebSystemTools.ConfigurationEncrypt" Version="1.0.9686.34761" />
    <PackageVersion Include="WebSystemTools.SerilogLogger" Version="1.0.9686.34761" />
    <PackageVersion Include="WebSystemTools.StaticFilesTools" Version="1.0.9686.34761" />
    <PackageVersion Include="WebSystemTools.SwaggerTools" Version="1.0.9686.34761" />
    <PackageVersion Include="WebSystemTools.TestToolsApi" Version="1.0.9686.34761" />
    <PackageVersion Include="WebSystemTools.WindowsServiceTools" Version="1.0.9686.34761" />
  </ItemGroup>
</Project>